<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260703093940 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE activity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ACTIVITY_NAME ON activity (name)');
        $this->addSql('CREATE TABLE activity_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, result VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, player_id INT NOT NULL, activity_id INT NOT NULL, vocabulary_id INT DEFAULT NULL, difficulty_id INT NOT NULL, session_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FD06F64799E6F5DF ON activity_log (player_id)');
        $this->addSql('CREATE INDEX IDX_FD06F64781C06096 ON activity_log (activity_id)');
        $this->addSql('CREATE INDEX IDX_FD06F647AD0E05F6 ON activity_log (vocabulary_id)');
        $this->addSql('CREATE INDEX IDX_FD06F647FCFA9DAE ON activity_log (difficulty_id)');
        $this->addSql('CREATE INDEX IDX_FD06F647613FECDF ON activity_log (session_id)');
        $this->addSql('CREATE TABLE difficulty (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(20) NOT NULL, label_jp VARCHAR(20) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DIFFICULTY_NAME ON difficulty (name)');
        $this->addSql('CREATE TABLE hiragana (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, character VARCHAR(5) NOT NULL, romaji VARCHAR(10) NOT NULL, position INT NOT NULL, stroke_count INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_HIRAGANA_CHARACTER ON hiragana (character)');
        $this->addSql('CREATE TABLE hiragana_group (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, type VARCHAR(30) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_HIRAGANA_GROUP_NAME ON hiragana_group (name)');
        $this->addSql('CREATE TABLE hiragana_group_member (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, hiragana_id INT NOT NULL, hiragana_group_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_58086252DF5749A1 ON hiragana_group_member (hiragana_id)');
        $this->addSql('CREATE INDEX IDX_58086252CD45C98E ON hiragana_group_member (hiragana_group_id)');
        $this->addSql('CREATE TABLE level_settings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, base_xp INT NOT NULL, increment INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ended_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, total_xp INT DEFAULT NULL, player_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D044D5D499E6F5DF ON session (player_id)');
        $this->addSql('CREATE TABLE "users" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, username VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "users" (email)');
        $this->addSql('CREATE TABLE vocabulary (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, hiragana VARCHAR(50) NOT NULL, romaji VARCHAR(50) NOT NULL, french VARCHAR(100) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, difficulty_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9099C97BFCFA9DAE ON vocabulary (difficulty_id)');
        $this->addSql('CREATE TABLE vocabulary_hiragana (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position INT NOT NULL, vocabulary_id INT NOT NULL, hiragana_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EA7C87F4AD0E05F6 ON vocabulary_hiragana (vocabulary_id)');
        $this->addSql('CREATE INDEX IDX_EA7C87F4DF5749A1 ON vocabulary_hiragana (hiragana_id)');
        $this->addSql('CREATE TABLE xp_rule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, xp_success INT NOT NULL, xp_failure INT NOT NULL, activity_id INT NOT NULL, difficulty_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9416673981C06096 ON xp_rule (activity_id)');
        $this->addSql('CREATE INDEX IDX_94166739FCFA9DAE ON xp_rule (difficulty_id)');
        $this->addSql('CREATE TABLE xp_transaction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, player_id INT NOT NULL, activity_log_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E526D97099E6F5DF ON xp_transaction (player_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E526D970B811BD86 ON xp_transaction (activity_log_id)');
        $this->addSql('ALTER TABLE activity_log ADD CONSTRAINT FK_FD06F64799E6F5DF FOREIGN KEY (player_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE activity_log ADD CONSTRAINT FK_FD06F64781C06096 FOREIGN KEY (activity_id) REFERENCES activity (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE activity_log ADD CONSTRAINT FK_FD06F647AD0E05F6 FOREIGN KEY (vocabulary_id) REFERENCES vocabulary (id)');
        $this->addSql('ALTER TABLE activity_log ADD CONSTRAINT FK_FD06F647FCFA9DAE FOREIGN KEY (difficulty_id) REFERENCES difficulty (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE activity_log ADD CONSTRAINT FK_FD06F647613FECDF FOREIGN KEY (session_id) REFERENCES session (id)');
        $this->addSql('ALTER TABLE hiragana_group_member ADD CONSTRAINT FK_58086252DF5749A1 FOREIGN KEY (hiragana_id) REFERENCES hiragana (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE hiragana_group_member ADD CONSTRAINT FK_58086252CD45C98E FOREIGN KEY (hiragana_group_id) REFERENCES hiragana_group (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE session ADD CONSTRAINT FK_D044D5D499E6F5DF FOREIGN KEY (player_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vocabulary ADD CONSTRAINT FK_9099C97BFCFA9DAE FOREIGN KEY (difficulty_id) REFERENCES difficulty (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vocabulary_hiragana ADD CONSTRAINT FK_EA7C87F4AD0E05F6 FOREIGN KEY (vocabulary_id) REFERENCES vocabulary (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vocabulary_hiragana ADD CONSTRAINT FK_EA7C87F4DF5749A1 FOREIGN KEY (hiragana_id) REFERENCES hiragana (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE xp_rule ADD CONSTRAINT FK_9416673981C06096 FOREIGN KEY (activity_id) REFERENCES activity (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE xp_rule ADD CONSTRAINT FK_94166739FCFA9DAE FOREIGN KEY (difficulty_id) REFERENCES difficulty (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE xp_transaction ADD CONSTRAINT FK_E526D97099E6F5DF FOREIGN KEY (player_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE xp_transaction ADD CONSTRAINT FK_E526D970B811BD86 FOREIGN KEY (activity_log_id) REFERENCES activity_log (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE activity_log DROP CONSTRAINT FK_FD06F64799E6F5DF');
        $this->addSql('ALTER TABLE activity_log DROP CONSTRAINT FK_FD06F64781C06096');
        $this->addSql('ALTER TABLE activity_log DROP CONSTRAINT FK_FD06F647AD0E05F6');
        $this->addSql('ALTER TABLE activity_log DROP CONSTRAINT FK_FD06F647FCFA9DAE');
        $this->addSql('ALTER TABLE activity_log DROP CONSTRAINT FK_FD06F647613FECDF');
        $this->addSql('ALTER TABLE hiragana_group_member DROP CONSTRAINT FK_58086252DF5749A1');
        $this->addSql('ALTER TABLE hiragana_group_member DROP CONSTRAINT FK_58086252CD45C98E');
        $this->addSql('ALTER TABLE session DROP CONSTRAINT FK_D044D5D499E6F5DF');
        $this->addSql('ALTER TABLE vocabulary DROP CONSTRAINT FK_9099C97BFCFA9DAE');
        $this->addSql('ALTER TABLE vocabulary_hiragana DROP CONSTRAINT FK_EA7C87F4AD0E05F6');
        $this->addSql('ALTER TABLE vocabulary_hiragana DROP CONSTRAINT FK_EA7C87F4DF5749A1');
        $this->addSql('ALTER TABLE xp_rule DROP CONSTRAINT FK_9416673981C06096');
        $this->addSql('ALTER TABLE xp_rule DROP CONSTRAINT FK_94166739FCFA9DAE');
        $this->addSql('ALTER TABLE xp_transaction DROP CONSTRAINT FK_E526D97099E6F5DF');
        $this->addSql('ALTER TABLE xp_transaction DROP CONSTRAINT FK_E526D970B811BD86');
        $this->addSql('DROP TABLE activity');
        $this->addSql('DROP TABLE activity_log');
        $this->addSql('DROP TABLE difficulty');
        $this->addSql('DROP TABLE hiragana');
        $this->addSql('DROP TABLE hiragana_group');
        $this->addSql('DROP TABLE hiragana_group_member');
        $this->addSql('DROP TABLE level_settings');
        $this->addSql('DROP TABLE session');
        $this->addSql('DROP TABLE "users"');
        $this->addSql('DROP TABLE vocabulary');
        $this->addSql('DROP TABLE vocabulary_hiragana');
        $this->addSql('DROP TABLE xp_rule');
        $this->addSql('DROP TABLE xp_transaction');
    }
}
